// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow that provides AI-powered feedback on interview answers.
 *
 * - provideAiFeedback - A function that handles the process of providing feedback on an interview answer.
 * - ProvideAiFeedbackInput - The input type for the provideAiFeedback function.
 * - ProvideAiFeedbackOutput - The return type for the provideAiFeedback function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const ProvideAiFeedbackInputSchema = z.object({
  question: z.string().describe('The interview question that was asked.'),
  answer: z.string().describe('The answer provided by the interviewee.'),
});
export type ProvideAiFeedbackInput = z.infer<typeof ProvideAiFeedbackInputSchema>;

const ProvideAiFeedbackOutputSchema = z.object({
  feedback: z.string().describe('AI-powered feedback on the interview answer, including clarity, completeness, and relevance.'),
});
export type ProvideAiFeedbackOutput = z.infer<typeof ProvideAiFeedbackOutputSchema>;

export async function provideAiFeedback(input: ProvideAiFeedbackInput): Promise<ProvideAiFeedbackOutput> {
  return provideAiFeedbackFlow(input);
}

const provideAiFeedbackPrompt = ai.definePrompt({
  name: 'provideAiFeedbackPrompt',
  input: {
    schema: z.object({
      question: z.string().describe('The interview question that was asked.'),
      answer: z.string().describe('The answer provided by the interviewee.'),
    }),
  },
  output: {
    schema: z.object({
      feedback: z.string().describe('AI-powered feedback on the interview answer, including clarity, completeness, and relevance.'),
    }),
  },
  prompt: `You are an AI-powered interview coach providing feedback on interview answers.

  Provide feedback on the clarity, completeness, and relevance of the answer.

  Question: {{{question}}}
  Answer: {{{answer}}}
  `,
});

const provideAiFeedbackFlow = ai.defineFlow<
  typeof ProvideAiFeedbackInputSchema,
  typeof ProvideAiFeedbackOutputSchema
>(
  {
    name: 'provideAiFeedbackFlow',
    inputSchema: ProvideAiFeedbackInputSchema,
    outputSchema: ProvideAiFeedbackOutputSchema,
  },
  async input => {
    const {output} = await provideAiFeedbackPrompt(input);
    return output!;
  }
);
